[package]
name = "metaview"
version = "0.1.0"
authors = ["Jakub HlusiÄka <limeth@protonmail.com>"]

[dependencies]
vulkano = "0.10.0"
vulkano-shader-derive = "0.10.0"
vulkano-win = "0.10.0"
winit = "0.17.0"
image = "0.19.0"
typenum = "1.10.0"
gltf = "0.11.2"
byteorder = "1.2.4"
failure = "0.1.2"
