[package]
name = "ammolite-math"
version = "0.1.0"
authors = ["Jakub HlusiÄka <limeth@protonmail.com>"]
edition = "2018"

[dependencies]
typenum = "1.10.0"
det = "0.1.0"
generic-array = "0.13.2"
serde = { version = "1.0", features = ["derive"] }
